<a href="https://colab.research.google.com/github/Lawrence-Krukrubo/AI_Nanodegree/blob/master/linear_algebra_refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Points and Vectors:**

Two fundamentals in Geometry are:-

1. Points: Essentially a point is a location in space, represented visually as a dot. In the cartesian system, a point is an ordered pair of coordinates $(x,y)$ first the $x$ and the $y$. 

2. Vectors: A vector is an object representing a change in position. In Euclidean space, a vector can be compared to an arrow connecting two points. The important properties of a vector in euclidean space are its **magnitude** meaning the length of the arrow and its **direction**. For example vector $[{2 \over 4}]$ means it goes 2 on the $x$ axis and 4 on the $y$ axis.

**Difference btwn a Point and Vector:**
1. A vec does not have a fixed location.
2. Two vectors are equal if they represent the same amt of change in each direction. While two points are equal only if they are located in the same place. 

### Adding and Subtracting vectors

Matrices and Vectors work very well with numpy...

In [0]:
import numpy as np
import pandas as pd

In [0]:
class Vector(object):
    def __init__(self, coordinates):

        self.coordinates = coordinates

        # Let's confirm its an iterable of atleast 2 elements.
        try:
            self.dimensions = len(coordinates) 
        except Exception as e:
            print(e)
            print('Kindly pass a List or Tuple of real numbers')

        if self.dimensions < 2:
            raise ValueError('Minimum of two elements must be in coordinates')
        
        for i in self.coordinates:
            try:
                int(i)
            except:
                raise ValueError('Elements Must be Type Int or Float')


    def add_vectors(*args):
        """This method takes a tuple or list of equal lenghts and converts
        same to an array and adds them up element-wise and returns an array."""

        first = np.zeros((np.array(args[0]).shape))

        try:
            for i in  args:
                first = first + np.array(i)
            return np.round(first,5)
        except Exception as e:
            return e
        

    def minus_vectors(*args):
        """This method takes a Vector object (self) and another numerical
        iterable of same length with self and adds them up element wise,
        finally it returns a numpy array
        """
        first = np.array(args[0])

        try:
            for i in  range(1, len(args)):
                first = first - np.array(args[i])
            return np.round(first,5)
        except Exception as e:
            return e
    

    def scalar_multiply(scalar, vector):
        """This method takes a scalar of any real number
        and a vec_or_mat object of type tuple or list, or numpy array
        containing real numbers. It returns an array of vec_or-mat,
        having each of its element multiplied by the scalar"""

        # Let's assert scalar is a real number i.e int or float
        # Let's assert only lists or tuples or arrays are vec_or_mat.
        try:
            assert type(scalar) is int or type(scalar) is float
        except:
            return 'Error: Scalar must be a real number'

        # Convert the vector object to a numpy array
        vector = np.array(vector)

        try:
            return np.round(scalar * vector, 5)
        except Exception as e:
            return e


    def magnitude(vector):
        """This method takes any given vector in
        form of an array, list or tuple and returns
        the magnitude or length of the vector"""

        vector = np.array(vector)

        magnitude = np.sqrt(np.sum(vector**2))

        return np.round(magnitude, 5)


    def normalize_vector(vector):
        """ This method takes a vector of type
        list, array or tuple and returns the the unit vector
        """
        vector = np.array(vector)

        vec_magnitude = Vector.magnitude(vector)

        # If magnitude is 0, meaning it's a Zero-Vector, then return Zero.
        if vec_magnitude:
            norm_vector = (1 / vec_magnitude) * vector
        else:
            return 0

        # Next let's verify that norm_vector is indeed a unit vector
        def confirm_unit_vector(norm_vector):
            """Let's find the magnitude or length
            of the unit vector if its 1 or very colse to one then we're okay
            """
            norm_vec_mag = Vector.magnitude(norm_vector)

            return norm_vec_mag
        
        unit_vec_magnitude = confirm_unit_vector(norm_vector)

        if 1 - unit_vec_magnitude > 0.05:
            return 'Not Quite a Unit Vector.'

        return np.round(norm_vector,5)


    def dot_product(vec_1, vec_2):
        """This method takes a Vector object (self) and another numerical
        iterable of same length with self and returns the sum of element-wise 
        multiplication on both vectors as a number
        """
        # Let's convert them to numpy arrays
        vec1 = np.array(vec_1)
        vec2 = np.array(vec_2)

        # Let's confirm both vectors are same length and contain ints or floats
        try:
            dot_sum = np.dot(vec_1, vec_2)
        except Exception as e:
            print(e)
            return 'Confirm Equal Lengths and Elements of only Type int or float'

        return np.round(dot_sum, 5)


    def vec_angle_degrees(vec_1, vec_2):
        """This method calculates the angle between two vectors
        in degrees and returns a float."""

        try:
            dot_sum = Vector.dot_product(vec_1, vec_2)
            mag_vec1 = Vector.magnitude(vec_1)
            mag_vec2 = Vector.magnitude(vec_2)
            cos_theta = dot_sum / (mag_vec1 * mag_vec2)
            theta = np.arccos(cos_theta) # radians of the degree
            degrees = np.degrees(theta)
            return np.round(degrees,5)
        except Exception as e:
            return e 


    def is_parallel(vec_1, vec_2):
        """This method checks if two vectors are parallel, That is, if one is 
        a scalar multiple of the other. It will confirm if the angle between
        the vectors is 0 or 180 and return True or False"""

        mag_vec1 = Vector.magnitude(vec_1)
        mag_vec2 = Vector.magnitude(vec_2)

        if (-0.05 <= mag_vec1 <= 0.05) or (-0.05 <= mag_vec2 <= 0.05):
            return True

        else:
            return Vector.vec_angle_degrees(vec_1,vec_2) == 180


        pass

    def is_orthogonal(vec1, vec2, ):
        """This method checks if two vectors are orthogonal. that is, if the
        dot product of the two vectors is equal to zero. This condition means
        one is a zero-vector or both are at right angle to one another"""

        try:
            dot_sum = Vector.dot_product(vec1,vec2)
        except Exception as e:
            print(e)
            return 'Confirm Equal Lengths and Elements of only Type int or float'

        return -0.05 <= dot_sum <= 0.05

    def vee_parallel(vec_v, vec_b):
        """Given two vectors; vec_v and vec_b,This method computes 
        the projection (v-parallel) of vec_v on vec_b.
        It returns an array of vector coordinates."""

        # first we find the unit vector of the basis vector
        unit_b = Vector.normalize_vector(vec_b)

        # Then the dot product of vec_v and the unit_vector_b
        vec_v_dot_unit_b = Vector.dot_product(vec_v, unit_b)
        try:
            projection = vec_v_dot_unit_b * unit_b
            return np.round(projection,5)
        except Exception as e:
            print(e)


    def vee_perp(vec_v, vec_b):
        """Given a projecting vector and a basis vector,
        find the components of the projecting vector, orthogonal
        to the basis vector (v-perp).
        it returns the orthogonal vector. An array."""

        # Now,Let's find the component of vec_v parallel to vec_b. (v-parallel)
        v_parallel = Vector.vee_parallel(vec_v, vec_b)

        # Therefore to find the orthogonal vec or V-perp, we subtract 
        # v_parallel from vec_v itself. Because, given a basis vector (vec_b),
        # We can express any vector as the sum of its component,parallel to the
        # basis vector and its component orthogonal to the basis vector.
        #
        try:
            v_perp = vec_v - v_parallel
            return v_perp
        except Exception as e:
            print(e)


    def cross_product(vec_v, vec_b):
        """This method finds the cross product of vec_v and vec_b
        in that order. length of vectors must be 3 or 2 dimensional.
        If either vectors is 2 dimensional a new dimension of 0
        is added to make 3 dimensions. This method returns a vector, which is
        formed by computing cross product of vec_v and vec_w."""

        try:
            assert 2 <= len(vec_v) < 4
            if len(vec_v) == 2:
                vec_v = list(vec_v)
                vec_v.append(0)
            assert 2 <= len(vec_b) < 4
            if len(vec_b) == 2:
                vec_b = list(vec_b)
                vec_b.append(0)
        except AssertionError as e:
            return 'vectors must contain either 2 or 3 elements only'

        cross_vec = np.zeros(len(vec_v))

        for i in range(len(cross_vec)):
            if i == 0:
                cross_vec[i] = (vec_v[1] * vec_b[2]) - (vec_b[1] * vec_v[2])
            elif i == 1:
                cross_vec[i] = -((vec_v[0] * vec_b[2]) - (vec_b[0] * vec_v[2]))
            else:
                cross_vec[i] = (vec_v[0] * vec_b[1]) - (vec_b[0] * vec_v[1])

        return cross_vec


    def area_parrallelogram(vec_v, vec_b):
        """ this method takes two vectors, vec_v and vec_b, which must 
        either be of size 2 or 3 elements. If elements are 2, a 3rd element 
        of 0 is appended. Then it returns the area of the parallelogram 
        formed by spanning, these two vectors.This area is just the square root
        of the magnitude of the cross-product of these two vectors."""

        # First we find the cross-product of vec_v and vec_b
        cross_vec = Vector.cross_product(vec_v, vec_b)
        # Next we find the magnitude of the cross-product-vector
        cross_vec_magnitude = Vector.magnitude(cross_vec)

        area_of_para = cross_vec_magnitude
        # finally we return the area, which is the magnitude computed here.
        return area_of_para


    def area_triangle(vec_v, vec_b):
        """ this method takes two vectors, vec_v and vec_b, which must 
        either be of size 2 or 3 elements. If elements are 2, a 3rd element 
        of 0 is appended. Then it returns the area of the traingle 
        formed by spanning, these two vectors.This area is just half of the 
        area of the parallelogram formed by these two vectors.."""

        area_of_para = Vector.area_parrallelogram(vec_v, vec_b)

        area_of_tri = 0.5 * area_of_para

        return area_of_tri

<b><h3>Note that multiplying a vector by a negative number reverses the direction of the vector in addition to possibly changing its magnitude.</b></h3>

lesson_2_quiz_1 let's add the following vectors

In [3]:
vec_1 = (8.218, -9.341)
vec_2 = (-1.129, 2.111)

# add them up
Vector.add_vectors(vec_1, vec_2)

array([ 7.089, -7.23 ])

lesson_2_quiz_2 let's minus the following vectors

In [4]:
vec_1 = (7.119, 8.215)
vec_2 = (-8.223, 0.878)

# minus 2 from 1
Vector.minus_vectors(vec_1, vec_2)

array([15.342,  7.337])

lesson_2_quiz_3 let's  scalar multiply the following vectors

In [5]:
x = 7.41
y = (1.671, -1.012, -0.318)
Vector.scalar_multiply(x,y)

array([12.38211, -7.49892, -2.35638])

## **Vector Normalization:**

This is the process of finding the unit vector and involves 2 steps:

1. Computing the magnitude of the vector 
2. Multiplying the inverse of the magnitude by the vector to normalise it (unit vector)

if vector is $v$ then its magnitude is **$\vert \vec v\vert$** and it's normalised or unit vector sign is **$\| \vec v\|$**

lesson_2_quiz_4 let's compute magnitude

In [6]:
x = [-0.221, 7.437]
Vector.magnitude(x)

7.44028

lesson_2_quiz_5 let's compute magnitude

In [7]:
x = [8.813, -1.331, -6.247]
Vector.magnitude(x)

10.88419

lesson_2_quiz_6 let's unit vector

In [8]:
x = [5.581, -2.136]
Vector.normalize_vector(x)

array([ 0.93394, -0.35744])

lesson_2_quiz_7 let's unit vector

In [9]:
x = [1.996, 3.108, -4.554]
Vector.normalize_vector(x)

array([ 0.3404 ,  0.53004, -0.77665])

### **Inner Product or Dot Product:**

This is one of the most important concepts in Linear Algebra. The inner or Dot product (since we always represent it by a dot between the vectors to be multiplied) lets us find the angle between two different vectors.
<br>It is calculated by first multiplying the corresponding coordinates of equal sized vectors and summing it up. The dot product is a number.

**Note That:** 
1. The magnitude of a vector is the square root of its dot-product on itself.
2. The Dot product of two vectors is a figure that is usually between the negative of the product of their magnitudes and the product of their magnitudes.

Let's calculate some dot products

In [10]:
x = (7.887, 4.138)
y = (-8.802, 6.776)

# Calculate the dot product
Vector.dot_product(x,y)

-41.38229

Proof that the magnitude of a vector is the square root of its dot product on itself.

In [11]:
Vector.magnitude(x)

8.90662

In [12]:
test = Vector.dot_product(x,x)
test = np.sqrt(test)
round(test,3)

8.907

Above test proven!!

In [13]:
x = (-5.955, -4.904, -1.874)
y = (-4.496, -8.755, 7.103)

# Calculate the dot product
Vector.dot_product(x,y)

56.39718

Let's calculate some angles of vectors

In [14]:
x = (3.183, -7.627)
y = (-2.668, 5.319)

# Let's calculate the angle in degrees
deg = Vector.vec_angle_degrees(x,y)

# Let's convert ot to radians
np.radians(deg)

3.0720243532040747

In [15]:
x = (7.35, 0.221, 5.188)
y = (2.751, 8.259, 3.985)

# Let's calculate the angle in degrees
Vector.vec_angle_degrees(x,y)

60.27582

### **Parallel and Orthogonal vectors:**
Parallel = <h3>$\vec v^{\|}$</h3>
Orthogonal = <h3>$\vec v^{\perp}$</h3>
1. **Parallel Vectors:**<br>
We say two vectors are parallel if one is a scalar multiple of the other. Thus vector $v$ is parallel to itself $(1 * v)$, $(0 * v)$, $(2 * v)$, $(0.5 * v)$... Even if they point in opposite direction such as $(-1 * v)$, all that matters is if one is a scalar multiple of the other. To be parallel, it means two vectors have an angle of zero or 180 degrees between them.
2. **Orthogonal Vectors:**<br>Two vectors are orthogonal if their dot product is equal to 0. This is possible in two situations:
>>A. Either one of the vectors is the zero-vector<br>
>>B. They are at **right-angled** to one another

The Zero-Vector: Is unique in that it is the only vector that is both parallel and orthogonal to all other vectors and it's the only vector orthogonal to itself. Note that if some vector is orthogonal to itself, then it must be the zero-vector.

**Coding Exercise: Checking for Parallelism and Orthogonality:**

In [16]:
x = (2.118, 4.827)
y = (0,0)
print(Vector.is_parallel(x,y),Vector.is_orthogonal(x,y))

True True


In [17]:
x = (-2.328, -7.284, -1.214)
y = (-1.821, 1.072, -2.94)
print(Vector.is_parallel(x,y),Vector.is_orthogonal(x,y))

False True


In [18]:
x = (-7.579, -7.88)
y = (22.737, 23.64)
print(Vector.is_parallel(x,y),Vector.is_orthogonal(x,y))

False False


### Projecting Vectors:

Orthogonality is a very powerful tool for decomposing objects into combinations of simpler objects in a structured way.

When a vector is projected from unto another vector, the perpendicular line between the projected vector and the base vector is called the 'perp'. If the projecting vector is $\vec v$ then the imaginary line with 90 degrees between it and the basis vector is called 'V- perp' symbolised as:- <h4>$\vec v^{\perp}$</h4>

Projecting a vector shows that the magnitude of the projected vector is the sum of it's parallel vector and the orthogonal vector perpendicular to the base vector:
<h3>$\| \vec v \| = \vec v^{\|} +  \vec v^{\perp}$</h3>

Thus given a non-zero basis vector, we can express any vector as the sum of two vectors<br>
>> One that's parallel to the basis vector <br>
>> And one that's orthogonal to the basis vector.

**SOH:** Sine of a Right-Angled Triangle is Opposite divided by the Hypothenuse<br>
**CAH:** Cosine of a Righy-Angled Triangle is Adjacent divided by the Hypothenuse.<br>
**TOA:** Cosine of a Righy-Angled Triangle is Adjacent divided by the Hypothenuse. 

Note that the length ov v-parallel is the length of v times the unit vector in the direction of vector b, which is parallel to v-parallel.
<h3>$|\vec v^{\|}| = | \vec v | * \| \vec b\|$</h3>
This can be extrapolated to mean
<h3>$\vec v^{\|} = (\vec v . \| \vec b \|)* \| \vec b\|$</h3>

<h4>Calculating vector projections, orthogonals and decomposing vectors</h4>

In [19]:
# Calculate the projection of vec_v on vec_b
vec_v = (3.039, 1.879)
vec_b = (0.825, 2.036)

Vector.vee_parallel(vec_v, vec_b)

array([1.08262, 2.67173])

In [20]:
# Find the component of vec_v, orthogonal to the basis vec_b.
vec_v = (-9.88, -3.264, -8.159)
vec_b = (-2.155, -9.353, -9.473)

Vector.vee_perp(vec_v, vec_b)

array([-8.35008,  3.37612, -1.43367])

In [21]:
# now find the components of vec_v parallel to vec_b and the orthogonal component of vec_v on vec_b
vec_v = (3.009, -6.172, 3.692, -2.51)
vec_b = (6.404, -9.144, 2.759, 8.718)

v_parallel_b = Vector.vee_parallel(vec_v, vec_b)
v_perp_b = Vector.vee_perp(vec_v, vec_b)
print(v_parallel_b, v_perp_b)

[ 1.96851 -2.81077  0.84807  2.67983] [ 1.04049 -3.36123  2.84393 -5.18983]


<h3><b>Cross-Products, Area-of-Parallelogram and Area of Triangle:</b></h3>

Cross products are another type of vector multiplications that only exist in 3-Dimensions. Unlike a dot-product that returns a number, cross-products return a vector. Geometrically, the cross-product of vectors $v$ and $w$, is the vector orthogonal to both $v$ and $w$. Cross products are non-commutative, this means the order matters as cross product of $v$ * $w$ != that of $w$ * $v$.
<h4>$\|\vec v*\vec w\| = \|\vec v\| * \|\vec w\| * sin\theta$</h4>
<br>The cross-product-vector of vectors $v$ and $w$ has a magnitude equal to the product of the magnitudes of the two composing vectors and sin of theta. Where theta is the angle between the two vectors. Note that if theta is $\pi$ $(180^o)$ or if theta is $0^o$, then the cross product will have magnitude of 0. In other words, the cross product of two parallel vectors is the zero-vector. Also, if either $v$ or $w$ is the zero-vector, then the cross product will be the zero-vector as well.

Area of Parallelogram:
Given two vectors $v$ and $w$, originating from the same point and taking $w$ as the base. We can form a parallelogram. First we take $w$ as the base of the parallelogram and $v$ is the hypothenuse of the right angled triangle formed by appending the orthogonal component of $v$ unto $b$. This orthogonal component is the height of the parallelogram formed from $v$ and $w$. 
<br>Using SOH, we can say the sin of theta is equal to the opposite over hypothenuse. which means. the height of the parallelogram is equal to the magnitude of vector $v$ times the sin of theta.<br>Therefore the area of a parallelogram fromed by two vectors is ofcourse the $height * base$. And the area of a triangle is half of the area of a parallelogram, so area of traingle is $0.5 * (height * base)$ of the paralleloram.
This simply means the area of a parallelogram formed by $v$ and $w$ is the magnitude of the cross-product of $v$ and $w$.

In [69]:
# find the cross-product of the following vectors
vec_v = (8.462, 7.893, -8.187)
vec_b = (6.984, -5.975, 4.778)
Vector.cross_product(vec_v, vec_b)

array([ -11.204571,  -97.609444, -105.685162])

In [70]:
# Find the area of the parallelogram spanned by these two vectors
vec_v = (-8.987, -9.838, 5.031)
vec_b = (-4.268, -1.861, -8.866)
Vector.area_parrallelogram(vec_v, vec_b)

142.12222

In [71]:
# Find the area of the triangle spanned by these two vectors
vec_v = (1.5, 9.547, 3.691)
vec_b = (-6.007, 0.124, 5.772)
Vector.area_triangle(vec_v, vec_b)

42.564935